#
#Mon Oct 19 10:36:22 CST 2020
blob_commit_prefix=..\\blobInfo\\CC_OUT\\blobId
jdbc.maxActive=100
jdbc.password=111111
jdbc.url=jdbc\:mysql\://localhost\:3306/code_clone_check?useSSL\=false&serverTimezone\=Asia/Shanghai&autoReconnect\=true&characterEncoding\=utf-8&allowPublicKeyRetrieval\=true
project=H\:\\WinterHolidayTask\\Dataset\\redis
start_group_id=1
jdbc.username=root
end_group_id=0
jdbc.driver=com.mysql.cj.jdbc.Driver
commit_info=..\\blobInfo\\CC_OUT\\commitInfo.csv
jdbc.initialSize=4
blob_prefix=..\\blobInfo\\CC_OUT\\blobs
max_instance=0
thread_number=10
language=c
isMulti=no
table=MeasureIndex_redisnoStruct
deleted_file_info=..\\blobInfo\\CC_OUT\\removePathList.csv
blobSnapshotMapResult=..\\map_result2.txt
