#
#Mon Oct 19 10:36:22 CST 2020
minLine=5
mlcc=10
useGPU=0
language=c
threshold=0.7
openStringHash=1
granularity=method
useLongType=0
extensions=c,h
tokenize=1
sepNum=100000000
mlc=50
exe=.\\executable\\executable_gpu_win10.exe
