#
#Mon Oct 19 10:36:22 CST 2020
resultFolder=.\\resultFolder
jdbc.password=111111
bufferCount=4000
threadNum=10
jdbc.url=jdbc\:mysql\://localhost\:3306/code_clone_check?useSSL\=false&serverTimezone\=Asia/Shanghai&autoReconnect\=true&characterEncoding\=utf-8&allowPublicKeyRetrieval\=true
CC_OUT=..\\blobInfo\\CC_OUT
measureIndexTbName=MeasureIndex_redisnoStruct
jdbc.username=root
jdbc.driver=com.mysql.cj.jdbc.Driver
detectFolder=..\\detect\\result
