#
#Mon Oct 19 10:36:22 CST 2020
extractedPath=all
repoPath=H\:\\WinterHolidayTask\\Dataset\\redis
outputInterval=200
startCommit=ed9b544e10b84cd43348ddfab7068b610a5df1f7
commitInterval=1
endCommit=324e22accf457edc996971bc97f5474349cd7c4c
outputFolder=.\\CC_OUT
suffix=c,h
traceCommit=overall-detection
