#
#Mon Oct 19 10:36:22 CST 2020
useBugInfo=1
lowCCP=0.2
highCCP=0.5
maxCloneInstanceNum=5
isMulti=no
CPI=2
consisResultFolder=.\\consistResult
keyWordList=bug,fix,fail,problem
extractedJsonFolder=.\\extractedJson
commit_info=..\\blobInfo\\CC_OUT\\commitInfo.csv
lowCCD=7
inputJsonFolder=..\\cloneEvo\\LinkResults
highCCD=30
outputPairFolder=.\\result
