#repoPath: 单项目所在目录的绝对路径。 填写示范：repoPath=/Users/dataset/redis
#startCommit： 分析的开始commit。填写示范： startCommit=ed9b544e10b84cd43348ddfab7068b610a5df1f7
#endCommit: 分析的结束commit。填写示范： endCommit=324e22accf457edc996971bc97f5474349cd7c4c
#traceCommit: 指定要分析的单版本commit，通常与endCommit一致，overall-detection，则全量检测。填写示范： traceCommit=324e22accf457edc996971bc97f5474349cd7c4c
#threadNum: 线程数。填写示范： threadNum=10
#projectName: 项目名，用于拼接数据库中的表名。 填写示范： projectName=redis  则数据库中对应的表名为MeasureIndex_redis
#language： 待分析项目的语言。 填写示范：language=c
#suffix: 待分析项目语言的代码文件后缀名，若有多个使用英文逗号分隔。 填写示范：suffix=c,h
#ip: 数据库的ip。 填写示范：ip=localhost
#database: 数据库名。 填写示范：database=code_clone_check
#username: 数据库用户名。 填写示范：username=root
#password: 数据库密码。 填写示范：password=root
#sepNum: 克隆检测数据分块大小。 填写示范：sepNum=200000000
#keyWordList: 用于提取commitMessage中bug信息的关键字
#exeName: 可执行程序名，根据平台选择。 填写示范：exeName=executable_gpu_linux
#commitInterval: 挑选commit的间隔。 填写示范：commitInterval=1
#extractedPath: 过滤出指定目录的blob，当前没有用到。 填写示范：extractedPath=src/
#blobSnapshotMapResult: 用clone_group_map3.py跑出的数据。 填写示范：blobSnapshotMapResult=../map_result2.txt
#
#Fri Sep 25 16:16:51 CST 2020
password=111111
threadNum=10
suffix=c,h
commitInterval=1
username=root
projectName=redisnoStruct
extractedPath=all
ip=localhost
endCommit=324e22accf457edc996971bc97f5474349cd7c4c
startCommit=ed9b544e10b84cd43348ddfab7068b610a5df1f7
repoPath=H:\\WinterHolidayTask\\Dataset\\redis
database=code_clone_check
urlParams=useSSL\=false&serverTimezone\=Asia/Shanghai&autoReconnect\=true&characterEncoding\=utf-8&allowPublicKeyRetrieval\=true
keyWordList=bug,fix,fail,problem
language=c
traceCommit=overall-detection
sepNum=100000000
exeName=executable_gpu_win10.exe
blobSnapshotMapResult=..\\map_result2.txt
